package icmp

import (
	"strconv"
	"time"

	"bgscan/internal/core/config"
	"bgscan/internal/core/config/validate"
	"bgscan/internal/logger"
	"bgscan/internal/ui/components/basic/input"
	"bgscan/internal/ui/components/basic/input/textinput"
	"bgscan/internal/ui/components/basic/inspector"
	"bgscan/internal/ui/components/basic/notice"
	"bgscan/internal/ui/shared/env"
	"bgscan/internal/ui/shared/ui"

	tea "charm.land/bubbletea/v2"
)

const groupICMP = "ICMP Settings"

const (
	descWorkers      = "The number of concurrent workers sending ICMP echo requests. Higher values increase scan speed at the cost of greater CPU and network utilization."
	descTimeout      = "Maximum duration in milliseconds to wait for an ICMP reply. Targets failing to respond within this window are considered unreachable."
	descTries        = "The maximum number of retry attempts per target to mitigate packet loss. Higher values improve reliability but increase total scan duration."
	descOutputPrefix = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."
)

type Model struct {
	state     *ui.AppState
	name      string
	id        ui.ComponentID
	inspector ui.Component
}

func (m *Model) ID() ui.ComponentID { return m.id }
func (m *Model) Init() tea.Cmd      { return nil }
func (m *Model) Mode() env.Mode     { return env.NormalMode }
func (m *Model) Name() string       { return m.name }
func (m *Model) OnClose() tea.Cmd   { return nil }

func saveICMP(state *ui.AppState) tea.Cmd {
	if err := state.Store.SaveICMP(state.Config.ICMP); err != nil {
		logger.UIError("Failed to save ICMP settings: %v", err)
		return notice.NewNoticeCmd(state.Layout, "Failed to save ICMP settings", err.Error(), notice.NOTICE_ERROR)
	}
	return nil
}

func New(state *ui.AppState, name string) *Model {
	cfg := &state.Config.ICMP

	workers := intInput(
		state, "Enter number of workers", cfg.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Workers = n
			return fieldErr(validate.ValidateICMP(tmp), "Workers")
		},
		func(n int) { cfg.Workers = n },
	)

	timeout := durationMSInput(
		state, "Enter timeout (milliseconds)", cfg.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateICMP(tmp), "Timeout")
		},
		func(d time.Duration) { cfg.Timeout = config.NewDurationMS(d) },
	)

	tries := intInput(
		state, "Enter maximum attempts", int(cfg.Tries),
		func(v string) error {
			n, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Tries = uint16(n)
			return fieldErr(validate.ValidateICMP(tmp), "Tries")
		},
		func(n int) { cfg.Tries = uint16(n) },
	)

	prefixOutput := stringInput(
		state, "Enter output file prefix", cfg.OutputPrefix,
		func(v string) error {
			tmp := *cfg
			tmp.OutputPrefix = v
			return fieldErr(validate.ValidateICMP(tmp), "OutputPrefix")
		},
		func(v string) { cfg.OutputPrefix = v },
	)

	fields := []inspector.Field{
		{Name: "Workers", Description: descWorkers, Group: groupICMP, Input: inspector.Adapt(workers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Timeout", Description: descTimeout, Group: groupICMP, Input: inspector.Adapt(timeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "Tries", Description: descTries, Group: groupICMP, Input: inspector.Adapt(tries), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Prefix Output", Description: descOutputPrefix, Group: groupICMP, Input: inspector.Adapt(prefixOutput), Visible: alwaysVisible},
	}

	return &Model{state: state, name: name, id: ui.NewComponentID(), inspector: inspector.New(state.Layout, "icmp settings", fields)}
}

func alwaysVisible() bool { return true }

func fieldErr(errs map[string]error, field string) error { return errs[field] }

func intInput(state *ui.AppState, title string, value int, validate func(string) error, set func(int)) input.Input[string] {
	return textinput.New(state.Layout, title, textinput.WithValue(strconv.Itoa(value)), textinput.WithValidation(validate), textinput.WithFocus(), textinput.WithOnSubmit(func(v string) tea.Cmd {
		n, err := strconv.Atoi(v)
		if err != nil {
			return notice.NewNoticeCmd(state.Layout, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
		}
		set(n)
		return saveICMP(state)
	}))
}

func durationMSInput(state *ui.AppState, title string, value time.Duration, validate func(string) error, set func(time.Duration)) input.Input[string] {
	return textinput.New(state.Layout, title, textinput.WithValue(strconv.FormatInt(value.Milliseconds(), 10)), textinput.WithValidation(validate), textinput.WithFocus(), textinput.WithOnSubmit(func(v string) tea.Cmd {
		n, err := strconv.Atoi(v)
		if err != nil {
			return notice.NewNoticeCmd(state.Layout, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
		}
		set(time.Duration(n) * time.Millisecond)
		return saveICMP(state)
	}))
}

func stringInput(state *ui.AppState, title, value string, validate func(string) error, set func(string)) input.Input[string] {
	return textinput.New(state.Layout, title, textinput.WithValue(value), textinput.WithValidation(validate), textinput.WithFocus(), textinput.WithOnSubmit(func(v string) tea.Cmd {
		set(v)
		return saveICMP(state)
	}))
}
