package dns

import (
	"strconv"
	"strings"
	"time"

	"bgscan/internal/core/config"
	"bgscan/internal/core/config/validate"
	"bgscan/internal/ui/components/basic/input"
	"bgscan/internal/ui/components/basic/input/multiselect"
	"bgscan/internal/ui/components/basic/input/selectinput"
	"bgscan/internal/ui/components/basic/input/textinput"
	"bgscan/internal/ui/components/basic/input/toggleinput"
	"bgscan/internal/ui/components/basic/inspector"
	"bgscan/internal/ui/components/basic/notice"
	"bgscan/internal/ui/shared/env"
	"bgscan/internal/ui/shared/layout"
	"bgscan/internal/ui/shared/ui"

	tea "charm.land/bubbletea/v2"
	"charm.land/huh/v2"
)

const (
	groupResolver   = "Resolver"
	groupDPI        = "DPI"
	groupDNSTT      = "DNSTT"
	groupSlipStream = "SlipStream"
)

const (
	// Resolver
	descResolverWorkers        = "The number of concurrent workers sending DNS queries. Higher values increase scan speed at the cost of greater CPU and network utilization."
	descResolverProtocol       = "The transport protocol used for DNS queries: 'udp', 'tcp', or 'dot' (DNS-over-TLS)."
	descResolverDomain         = "The target domain name used as the primary query target for DNS resolution."
	descResolverPort           = "The target port used for DNS queries (typically 53)."
	descResolverCheckTypes     = "The DNS record types to query (e.g., A, AAAA, TXT). For DNSTT compatibility, 'TXT' is strongly recommended."
	descResolverEDNSBufSize    = "The EDNS0 buffer size in bytes advertised in OPT records. Set to 0 to disable."
	descResolverTimeout        = "Maximum duration in milliseconds to wait for a DNS response. Queries failing to respond within this window are considered failed."
	descResolverTries          = "The maximum number of network retry attempts per target to mitigate packet loss. Higher values improve reliability but increase total scan duration."
	descResolverRandomSub      = "Generates a random subdomain for each query to bypass resolver caches and force a fresh recursive lookup."
	descResolverAcceptedRCodes = "The DNS response codes treated as successful ('alive') results. Recommended: 'noerror', 'nxdomain'."

	// DPI
	descResolverCheckDPI     = "Enables the anti-hijacking pre-check. Queries a non-existent '.invalid' domain; if it returns success, the resolver is flagged as hijacked and discarded."
	descResolverDPITimeout   = "Maximum duration in milliseconds to wait for the DPI pre-check response. Typically set shorter than the main timeout."
	descResolverDPITries     = "The maximum number of network retry attempts for the DPI pre-check."
	descResolverPrefixOutput = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."

	// DNSTT
	descDNSTTEnabled      = "Enables or disables the DNSTT (DNS Tunnel Tool) probe phase."
	descDNSTTWorkers      = "The number of concurrent workers performing DNSTT handshakes."
	descDNSTTDomain       = "The authoritative DNS zone delegated to your DNSTT server."
	descDNSTTPublicKey    = "The public key of the DNSTT server (typically a Base64-encoded or hex string)."
	descDNSTTTimeout      = "Maximum duration in milliseconds to wait for a complete DNSTT handshake to finish."
	descDNSTTPrefixOutput = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."

	// SlipStream
	descSlipStreamEnabled      = "Enables or disables the SlipStream DNS probe phase."
	descSlipStreamWorkers      = "The number of concurrent workers performing SlipStream probes."
	descSlipStreamDomain       = "The authoritative DNS zone used by the SlipStream server."
	descSlipStreamCertPath     = "The file path to the TLS certificate used by the SlipStream server. Leave empty if not required."
	descSlipStreamTimeout      = "Maximum duration in milliseconds to wait for a complete SlipStream probe to finish."
	descSlipStreamPrefixOutput = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."
)

type Model struct {
	layout    *layout.Layout
	name      string
	id        ui.ComponentID
	inspector ui.Component
}

func (m *Model) ID() ui.ComponentID { return m.id }
func (m *Model) Init() tea.Cmd      { return nil }
func (m *Model) Mode() env.Mode     { return env.NormalMode }
func (m *Model) Name() string       { return m.name }
func (m *Model) OnClose() tea.Cmd   { return nil }

func saveDNS(l *layout.Layout, cfg *config.DNSConfig) tea.Cmd {
	if err := config.SaveDNSConfig(cfg); err != nil {
		return notice.NewNoticeCmd(l, "Failed to save DNS settings", err.Error(), notice.NOTICE_ERROR)
	}
	return nil
}

func intInput(l *layout.Layout, title string, value int, val func(string) error, set func(int), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.Itoa(value)),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(n)
			return save()
		}),
	)
}

func durationMSInput(l *layout.Layout, title string, value time.Duration, val func(string) error, set func(time.Duration), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(strconv.FormatInt(value.Milliseconds(), 10)),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(l, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(time.Duration(n) * time.Millisecond)
			return save()
		}),
	)
}

func stringInput(l *layout.Layout, title, value string, val func(string) error, set func(string), save func() tea.Cmd) input.Input[string] {
	return textinput.New(
		l, title,
		textinput.WithValue(value),
		textinput.WithFocus(),
		textinput.WithValidation(val),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			set(v)
			return save()
		}),
	)
}

func New(l *layout.Layout, name string) *Model {
	cfg := config.GetDNS()
	save := func() tea.Cmd { return saveDNS(l, cfg) }

	r := cfg.Resolver
	d := cfg.DNSTT
	s := cfg.SlipStream

	// ── Resolver ─────────────────────────────────────────────────────────────

	resolverWorkers := intInput(l, "Enter number of workers", r.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *r
			tmp.Workers = n
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{Resolver: &tmp}), "Resolver.Workers")
		},
		func(n int) { r.Workers = n }, save)

	resolverProtocol := selectinput.New(
		l, "Select protocol",
		selectinput.WithValue(r.Protocol),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("UDP", "udp"),
			huh.NewOption("TCP", "tcp"),
			huh.NewOption("DoT", "dot"),
		),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			r.Protocol = v
			return save()
		}),
	)

	resolverCheckType := multiselect.New(
		l, "Select check types",
		multiselect.WithFocus[string](),
		multiselect.WithOptions(
			huh.NewOption("A", "A"),
			huh.NewOption("AAAA", "AAAA"),
			huh.NewOption("CNAME", "CNAME"),
			huh.NewOption("NS", "NS"),
			huh.NewOption("MX", "MX"),
			huh.NewOption("TXT", "TXT"),
		),
		multiselect.WithValue(toUpper(r.CheckTypes)),
		multiselect.WithRequired[string](),
		multiselect.WithOnSubmit(func(v []string) tea.Cmd {
			r.CheckTypes = v
			return save()
		}),
	)

	resolverDomain := stringInput(
		l,
		"Enter target domain",
		r.Domain,
		func(v string) error {
			tmp := *cfg
			tmp.Resolver.Domain = v
			return fieldErr(validate.ValidateDNS(&tmp), "Resolver.Domain")
		}, func(v string) { r.Domain = v }, save,
	)

	resolverPort := intInput(
		l,
		"Enter port number",
		int(r.Port),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *r
			tmp.Port = uint16(n)
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{Resolver: &tmp}), "Resolver.Port")
		},
		func(n int) { r.Port = uint16(n) }, save,
	)

	resolverEDNSBufSize := intInput(l, "Enter EDNS buffer size", int(r.EDNSBufSize),
		func(v string) error { return nil },
		func(n int) { r.EDNSBufSize = uint16(n) }, save)

	resolverTimeout := durationMSInput(l, "Enter timeout (milliseconds)", r.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *r
			tmp.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{Resolver: &tmp}), "Resolver.Timeout")
		},
		func(d time.Duration) { r.Timeout = config.NewDurationMS(d) }, save)

	resolverTries := intInput(l, "Enter maximum attempts", r.Tries,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *r
			tmp.Tries = n
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{Resolver: &tmp}), "Resolver.Tries")
		},
		func(n int) { r.Tries = n }, save)

	resolverRandomSubdomain := toggleinput.New(
		l, "Enable random subdomain",
		toggleinput.WithValue(r.RandomSubdomain),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			r.RandomSubdomain = v
			return save()
		}),
	)

	resolverCheckDPI := toggleinput.New(
		l, "Enable DPI check",
		toggleinput.WithValue(r.CheckDPI),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			r.CheckDPI = v
			return save()
		}),
	)

	resolverAcceptedRCodes := multiselect.New(
		l, "Select accepted RCodes",
		multiselect.WithFocus[string](),
		multiselect.WithOptions(
			huh.NewOption("NOERROR", "NOERROR"),
			huh.NewOption("FORMERR", "FORMERR"),
			huh.NewOption("SERVFAIL", "SERVFAIL"),
			huh.NewOption("NXDOMAIN", "NXDOMAIN"),
			huh.NewOption("NOTIMP", "NOTIMP"),
			huh.NewOption("REFUSED", "REFUSED"),
		),
		multiselect.WithValue(toUpper(r.AcceptedRCodes)),
		multiselect.WithRequired[string](),
		multiselect.WithOnSubmit(func(v []string) tea.Cmd {
			r.AcceptedRCodes = v
			return save()
		}),
	)

	resolverDPITimeout := durationMSInput(l, "Enter DPI timeout (milliseconds)", r.DPITimeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *r
			tmp.DPITimeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{Resolver: &tmp}), "Resolver.DPITimeout")
		},
		func(dur time.Duration) { r.DPITimeout = config.NewDurationMS(dur) }, save)

	resolverDPITries := intInput(l, "Enter maximum DPI attempts", r.DPITries,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *r
			tmp.DPITries = n
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{Resolver: &tmp}), "Resolver.DPITries")
		},
		func(n int) { r.DPITries = n }, save)

	resolverPrefixOutput := stringInput(l,
		"Enter output file prefix",
		r.PrefixOutput,
		func(s string) error {
			tmp := *r
			tmp.PrefixOutput = s
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{Resolver: &tmp}), "Resolver.PrefixOutput")
		},
		func(v string) { r.PrefixOutput = v }, save)

	dpiEnabled := func() bool { return r.CheckDPI }

	// ── DNSTT ────────────────────────────────────────────────────────────────

	dnsttEnabled := toggleinput.New(
		l, "Enable DNSTT",
		toggleinput.WithValue(d.Enabled),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			d.Enabled = v
			return save()
		}),
	)

	dnsttWorkers := intInput(l, "Enter number of workers", d.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *d
			tmp.Workers = n
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{DNSTT: &tmp}), "DNSTT.Workers")
		},
		func(n int) { d.Workers = n }, save)

	dnsttDomain := stringInput(l, "Enter target domain", d.Domain,
		func(s string) error {
			tmp := *d
			tmp.Domain = s
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{DNSTT: &tmp}), "DNSTT.Domain")
		},
		func(v string) { d.Domain = v }, save)

	dnsttPublicKey := stringInput(l, "Enter public key", d.PublicKey,
		func(s string) error {
			tmp := *d
			tmp.PublicKey = s
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{DNSTT: &tmp}), "DNSTT.PublicKey")
		},
		func(v string) { d.PublicKey = v }, save)

	dnsttTimeout := durationMSInput(l, "Enter timeout (milliseconds)", d.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *d
			tmp.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{DNSTT: &tmp}), "DNSTT.Timeout")
		},
		func(dur time.Duration) { d.Timeout = config.NewDurationMS(dur) }, save)

	dnsttPrefixOutput := stringInput(l, "Enter output file prefix", d.PrefixOutput,
		func(s string) error {
			tmp := *d
			tmp.PrefixOutput = s
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{DNSTT: &tmp}), "DNSTT.PrefixOutput")
		}, func(v string) { d.PrefixOutput = v }, save)

	dnsttActive := func() bool { return d.Enabled }

	// ── SlipStream ───────────────────────────────────────────────────────────

	slipStreamEnabled := toggleinput.New(
		l, "Enable SlipStream",
		toggleinput.WithValue(s.Enabled),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			s.Enabled = v
			return save()
		}),
	)

	slipStreamWorkers := intInput(l, "Enter number of workers", s.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *s
			tmp.Workers = n
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{SlipStream: &tmp}), "SlipStream.Workers")
		},
		func(n int) { s.Workers = n }, save)

	slipStreamDomain := stringInput(l, "Enter target domain", s.Domain,
		func(v string) error {
			tmp := *s
			tmp.Domain = v
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{SlipStream: &tmp}), "SlipStream.Domain")
		}, func(v string) { s.Domain = v }, save)

	slipStreamCertPath := stringInput(l, "Enter certificate path", s.CertPath,
		func(_ string) error { return nil }, func(v string) { s.CertPath = v }, save)

	slipStreamTimeout := durationMSInput(l, "Enter timeout (milliseconds)", s.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *s
			tmp.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{SlipStream: &tmp}), "SlipStream.Timeout")
		},
		func(dur time.Duration) { s.Timeout = config.NewDurationMS(dur) }, save)

	slipStreamPrefixOutput := stringInput(l, "Enter output file prefix", s.PrefixOutput,
		func(v string) error {
			tmp := *s
			tmp.PrefixOutput = v
			return fieldErr(validate.ValidateDNS(&config.DNSConfig{SlipStream: &tmp}), "SlipStream.PrefixOutput")
		},
		func(v string) { s.PrefixOutput = v }, save)

	slipStreamActive := func() bool { return s.Enabled }

	fields := []inspector.Field{
		// Resolver
		{Name: "Workers", Description: descResolverWorkers, Group: groupResolver, Input: inspector.Adapt(resolverWorkers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Protocol", Description: descResolverProtocol, Group: groupResolver, Input: inspector.Adapt(resolverProtocol), Visible: alwaysVisible},
		{Name: "Domain", Description: descResolverDomain, Group: groupResolver, Input: inspector.Adapt(resolverDomain), Visible: alwaysVisible},
		{Name: "Port", Description: descResolverPort, Group: groupResolver, Input: inspector.Adapt(resolverPort), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Check Types", Description: descResolverCheckTypes, Group: groupResolver, Input: inspector.Adapt(resolverCheckType), Visible: alwaysVisible, Format: inspector.FormatStringList},
		{Name: "EDNS Buffer Size", Description: descResolverEDNSBufSize, Group: groupResolver, Input: inspector.Adapt(resolverEDNSBufSize), Visible: alwaysVisible, Format: formatEDNS},
		{Name: "Timeout", Description: descResolverTimeout, Group: groupResolver, Input: inspector.Adapt(resolverTimeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "Tries", Description: descResolverTries, Group: groupResolver, Input: inspector.Adapt(resolverTries), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Random Subdomain", Description: descResolverRandomSub, Group: groupResolver, Input: inspector.Adapt(resolverRandomSubdomain), Visible: alwaysVisible, Format: inspector.FormatBool},
		{Name: "Accepted RCodes", Description: descResolverAcceptedRCodes, Group: groupResolver, Input: inspector.Adapt(resolverAcceptedRCodes), Visible: alwaysVisible, Format: inspector.FormatStringList},
		{Name: "Prefix Output", Description: descResolverPrefixOutput, Group: groupResolver, Input: inspector.Adapt(resolverPrefixOutput), Visible: alwaysVisible},

		// DPI
		{Name: "Check DPI", Description: descResolverCheckDPI, Group: groupDPI, Input: inspector.Adapt(resolverCheckDPI), Visible: alwaysVisible, Format: inspector.FormatBool},
		{Name: "DPI Timeout", Description: descResolverDPITimeout, Group: groupDPI, Input: inspector.Adapt(resolverDPITimeout), Visible: dpiEnabled, Format: inspector.FormatDurationMS},
		{Name: "DPI Tries", Description: descResolverDPITries, Group: groupDPI, Input: inspector.Adapt(resolverDPITries), Visible: dpiEnabled, Format: inspector.FormatInt},

		// DNSTT
		{Name: "Enabled", Description: descDNSTTEnabled, Group: groupDNSTT, Input: inspector.Adapt(dnsttEnabled), Visible: alwaysVisible, Format: inspector.FormatBool},
		{Name: "Workers", Description: descDNSTTWorkers, Group: groupDNSTT, Input: inspector.Adapt(dnsttWorkers), Visible: dnsttActive, Format: inspector.FormatInt},
		{Name: "Domain", Description: descDNSTTDomain, Group: groupDNSTT, Input: inspector.Adapt(dnsttDomain), Visible: dnsttActive},
		{Name: "Public Key", Description: descDNSTTPublicKey, Group: groupDNSTT, Input: inspector.Adapt(dnsttPublicKey), Visible: dnsttActive},
		{Name: "Timeout", Description: descDNSTTTimeout, Group: groupDNSTT, Input: inspector.Adapt(dnsttTimeout), Visible: dnsttActive, Format: inspector.FormatDurationMS},
		{Name: "Prefix Output", Description: descDNSTTPrefixOutput, Group: groupDNSTT, Input: inspector.Adapt(dnsttPrefixOutput), Visible: dnsttActive},

		// SlipStream
		{Name: "Enabled", Description: descSlipStreamEnabled, Group: groupSlipStream, Input: inspector.Adapt(slipStreamEnabled), Visible: alwaysVisible, Format: inspector.FormatBool},
		{Name: "Workers", Description: descSlipStreamWorkers, Group: groupSlipStream, Input: inspector.Adapt(slipStreamWorkers), Visible: slipStreamActive, Format: inspector.FormatInt},
		{Name: "Domain", Description: descSlipStreamDomain, Group: groupSlipStream, Input: inspector.Adapt(slipStreamDomain), Visible: slipStreamActive},
		{Name: "Cert Path", Description: descSlipStreamCertPath, Group: groupSlipStream, Input: inspector.Adapt(slipStreamCertPath), Visible: slipStreamActive},
		{Name: "Timeout", Description: descSlipStreamTimeout, Group: groupSlipStream, Input: inspector.Adapt(slipStreamTimeout), Visible: slipStreamActive, Format: inspector.FormatDurationMS},
		{Name: "Prefix Output", Description: descSlipStreamPrefixOutput, Group: groupSlipStream, Input: inspector.Adapt(slipStreamPrefixOutput), Visible: slipStreamActive},
	}

	return &Model{
		layout:    l,
		name:      name,
		id:        ui.NewComponentID(),
		inspector: inspector.New(l, "dns settings", fields),
	}
}

func alwaysVisible() bool { return true }

func toUpper(values []string) []string {
	out := make([]string, len(values))
	for i, v := range values {
		out[i] = strings.ToUpper(v)
	}
	return out
}

func fieldErr(errs map[string]error, field string) error {
	return errs[field]
}

func formatEDNS(v any) string {
	s, ok := v.(string)
	if !ok {
		return ""
	}

	if strings.TrimSpace(s) == "0" {
		return "disabled"
	}

	return inspector.FormatInt(v)
}
