package dns

import (
	"strconv"
	"strings"
	"time"

	"bgscan/internal/core/config"
	"bgscan/internal/core/config/validate"
	"bgscan/internal/logger"
	"bgscan/internal/ui/components/basic/input"
	"bgscan/internal/ui/components/basic/input/multiselect"
	"bgscan/internal/ui/components/basic/input/selectinput"
	"bgscan/internal/ui/components/basic/input/textinput"
	"bgscan/internal/ui/components/basic/input/toggleinput"
	"bgscan/internal/ui/components/basic/inspector"
	"bgscan/internal/ui/components/basic/notice"
	"bgscan/internal/ui/shared/env"
	"bgscan/internal/ui/shared/ui"

	tea "charm.land/bubbletea/v2"
	"charm.land/huh/v2"
)

const (
	groupResolver  = "Resolver"
	groupDPI       = "DPI"
	groupDNSTunnel = "DNS Tunneling"
)

const (
	// Resolver
	descResolverWorkers        = "The number of concurrent workers sending DNS queries. Higher values increase scan speed at the cost of greater CPU and network utilization."
	descResolverTransport      = "The transport protocol used for DNS queries: 'udp', 'tcp', or 'dot' (DNS-over-TLS)."
	descResolverDomain         = "The target domain name used as the primary query target for DNS resolution."
	descResolverPort           = "The target port used for DNS queries (typically 53)."
	descResolverCheckTypes     = "The DNS record types to query (e.g., A, AAAA, TXT). For DNSTT compatibility, 'TXT' is strongly recommended."
	descResolverEDNSBufSize    = "The EDNS0 buffer size in bytes advertised in OPT records. Set to 0 to disable."
	descResolverTimeout        = "Maximum duration in milliseconds to wait for a DNS response. Queries failing to respond within this window are considered failed."
	descResolverTries          = "The maximum number of network retry attempts per target to mitigate packet loss. Higher values improve reliability but increase total scan duration."
	descResolverRandomSub      = "Generates a random subdomain for each query to bypass resolver caches and force a fresh recursive lookup."
	descResolverAcceptedRCodes = "The DNS response codes treated as successful ('alive') results. Recommended: 'noerror', 'nxdomain'."
	descResolverOutputPrefix   = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."

	// DPI
	descResolverCheckDPI   = "Enables the anti-hijacking pre-check. Queries a non-existent '.invalid' domain; if it returns success, the resolver is flagged as hijacked and discarded."
	descResolverDPITimeout = "Maximum duration in milliseconds to wait for the DPI pre-check response. Typically set shorter than the main timeout."
	descResolverDPITries   = "The maximum number of network retry attempts for the DPI pre-check."

	// DNS Tunneling (shared across DNSTT / SlipStream / VayDNS probes)
	descTunnelWorkers          = "The number of concurrent workers performing DNS tunneling probes."
	descTunnelTries            = "The maximum number of attempts per target."
	descTunnelTimeout          = "Maximum duration in milliseconds to wait for a complete DNS tunneling probe to finish."
	descTunnelCheckDNSResolver = "Checks DNS resolver availability before testing the tunnel. Disable to test the tunnel directly."
	descTunnelOutputPrefix     = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."
)

type Model struct {
	state     *ui.AppState
	name      string
	id        ui.ComponentID
	inspector ui.Component
}

func (m *Model) ID() ui.ComponentID { return m.id }
func (m *Model) Init() tea.Cmd      { return nil }
func (m *Model) Mode() env.Mode     { return env.NormalMode }
func (m *Model) Name() string       { return m.name }
func (m *Model) OnClose() tea.Cmd   { return nil }

func saveDNS(state *ui.AppState) tea.Cmd {
	if err := state.Store.SaveDNS(state.Config.DNS); err != nil {
		logger.UIError("Failed to save DNS settings: %v", err)
		return notice.NewNoticeCmd(state.Layout, "Failed to save DNS settings", err.Error(), notice.NOTICE_ERROR)
	}
	return nil
}

func intInput(state *ui.AppState, title string, value int, validate func(string) error, set func(int)) input.Input[string] {
	return textinput.New(
		state.Layout, title,
		textinput.WithValue(strconv.Itoa(value)),
		textinput.WithValidation(validate),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(state.Layout, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(n)
			return saveDNS(state)
		}),
	)
}

func durationMSInput(state *ui.AppState, title string, value time.Duration, validate func(string) error, set func(time.Duration)) input.Input[string] {
	return textinput.New(
		state.Layout, title,
		textinput.WithValue(strconv.FormatInt(value.Milliseconds(), 10)),
		textinput.WithValidation(validate),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(state.Layout, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(time.Duration(n) * time.Millisecond)
			return saveDNS(state)
		}),
	)
}

func stringInput(state *ui.AppState, title, value string, validate func(string) error, set func(string)) input.Input[string] {
	return textinput.New(
		state.Layout, title,
		textinput.WithValue(value),
		textinput.WithFocus(),
		textinput.WithValidation(validate),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			set(v)
			return saveDNS(state)
		}),
	)
}

func New(state *ui.AppState, name string) *Model {
	cfg := &state.Config.DNS

	resolverWorkers := intInput(state, "Enter number of workers", cfg.Resolver.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Resolver.Workers = n
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.Workers")
		},
		func(n int) { cfg.Resolver.Workers = n })

	resolverTransport := selectinput.New(
		state.Layout, "Select protocol",
		selectinput.WithValue(cfg.Resolver.Transport),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("UDP", "udp"),
			huh.NewOption("TCP", "tcp"),
			huh.NewOption("DoT", "dot"),
		),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.Resolver.Transport = v
			return saveDNS(state)
		}),
	)

	resolverCheckType := multiselect.New(
		state.Layout, "Select check types",
		multiselect.WithFocus[string](),
		multiselect.WithOptions(
			huh.NewOption("A", "A"),
			huh.NewOption("AAAA", "AAAA"),
			huh.NewOption("CNAME", "CNAME"),
			huh.NewOption("NS", "NS"),
			huh.NewOption("MX", "MX"),
			huh.NewOption("TXT", "TXT"),
		),
		multiselect.WithValue(toUpper(cfg.Resolver.CheckTypes)),
		multiselect.WithRequired[string](),
		multiselect.WithOnSubmit(func(v []string) tea.Cmd {
			cfg.Resolver.CheckTypes = v
			return saveDNS(state)
		}),
	)

	resolverDomain := stringInput(
		state,
		"Enter target domain",
		cfg.Resolver.Domain,
		func(v string) error {
			tmp := *cfg
			tmp.Resolver.Domain = v
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.Domain")
		}, func(v string) { cfg.Resolver.Domain = v },
	)

	resolverPort := intInput(
		state,
		"Enter port number",
		int(cfg.Resolver.Port),
		func(v string) error {
			n, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Resolver.Port = uint16(n)
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.Port")
		},
		func(n int) { cfg.Resolver.Port = uint16(n) },
	)

	resolverEDNSBufSize := intInput(state, "Enter EDNS buffer size", int(cfg.Resolver.EDNSBufSize),
		func(v string) error { return nil },
		func(n int) { cfg.Resolver.EDNSBufSize = uint16(n) })

	resolverTimeout := durationMSInput(state, "Enter timeout (milliseconds)", cfg.Resolver.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Resolver.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.Timeout")
		},
		func(d time.Duration) { cfg.Resolver.Timeout = config.NewDurationMS(d) })

	resolverTries := intInput(state, "Enter maximum attempts", cfg.Resolver.Tries,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Resolver.Tries = n
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.Tries")
		},
		func(n int) { cfg.Resolver.Tries = n })

	resolverRandomSubdomain := toggleinput.New(
		state.Layout, "Enable random subdomain",
		toggleinput.WithValue(cfg.Resolver.RandomSubdomain),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			cfg.Resolver.RandomSubdomain = v
			return saveDNS(state)
		}),
	)

	resolverAcceptedRCodes := multiselect.New(
		state.Layout, "Select accepted RCodes",
		multiselect.WithFocus[string](),
		multiselect.WithOptions(
			huh.NewOption("NOERROR", "NOERROR"),
			huh.NewOption("FORMERR", "FORMERR"),
			huh.NewOption("SERVFAIL", "SERVFAIL"),
			huh.NewOption("NXDOMAIN", "NXDOMAIN"),
			huh.NewOption("NOTIMP", "NOTIMP"),
			huh.NewOption("REFUSED", "REFUSED"),
		),
		multiselect.WithValue(toUpper(cfg.Resolver.AcceptedRCodes)),
		multiselect.WithRequired[string](),
		multiselect.WithOnSubmit(func(v []string) tea.Cmd {
			cfg.Resolver.AcceptedRCodes = v
			return saveDNS(state)
		}),
	)

	resolverOutputPrefix := stringInput(state,
		"Enter output file prefix",
		cfg.Resolver.OutputPrefix,
		func(s string) error {
			tmp := *cfg
			tmp.Resolver.OutputPrefix = s
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.OutputPrefix")
		},
		func(v string) { cfg.Resolver.OutputPrefix = v })

	// DPI pre-check, nested under Resolver.DPI
	resolverCheckDPI := toggleinput.New(
		state.Layout, "Enable DPI check",
		toggleinput.WithValue(cfg.Resolver.DPI.Enabled),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			cfg.Resolver.DPI.Enabled = v
			return saveDNS(state)
		}),
	)

	resolverDPITimeout := durationMSInput(state, "Enter DPI timeout (milliseconds)", cfg.Resolver.DPI.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Resolver.DPI.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.DPI.Timeout")
		},
		func(dur time.Duration) { cfg.Resolver.DPI.Timeout = config.NewDurationMS(dur) })

	resolverDPITries := intInput(state, "Enter maximum DPI attempts", cfg.Resolver.DPI.Tries,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Resolver.DPI.Tries = n
			return fieldErr(validate.ValidateDNS(tmp), "Resolver.DPI.Tries")
		},
		func(n int) { cfg.Resolver.DPI.Tries = n })

	dpiEnabled := func() bool { return cfg.Resolver.DPI.Enabled }

	// DNS tunneling settings shared by DNSTT / SlipStream / VayDNS
	tunnelWorkers := intInput(state, "Enter number of workers", cfg.DNSTunneling.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.DNSTunneling.Workers = n
			return fieldErr(validate.ValidateDNS(tmp), "DNSTunneling.Workers")
		},
		func(n int) { cfg.DNSTunneling.Workers = n })

	tunnelTries := intInput(state, "Enter maximum attempts", cfg.DNSTunneling.Tries,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.DNSTunneling.Tries = n
			return fieldErr(validate.ValidateDNS(tmp), "DNSTunneling.Tries")
		},
		func(n int) { cfg.DNSTunneling.Tries = n })

	tunnelTimeout := durationMSInput(state, "Enter timeout (milliseconds)", cfg.DNSTunneling.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.DNSTunneling.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateDNS(tmp), "DNSTunneling.Timeout")
		},
		func(dur time.Duration) { cfg.DNSTunneling.Timeout = config.NewDurationMS(dur) })

	tunnelCheckDNSResolver := toggleinput.New(
		state.Layout, "Check resolver before tunneling",
		toggleinput.WithValue(cfg.DNSTunneling.CheckDNSResolver),
		toggleinput.WithFocus(),
		toggleinput.WithLabels("Enabled", "Disabled"),
		toggleinput.WithOnSubmit(func(v bool) tea.Cmd {
			cfg.DNSTunneling.CheckDNSResolver = v
			return saveDNS(state)
		}),
	)

	tunnelOutputPrefix := stringInput(state, "Enter output file prefix", cfg.DNSTunneling.OutputPrefix,
		func(s string) error {
			tmp := *cfg
			tmp.DNSTunneling.OutputPrefix = s
			return fieldErr(validate.ValidateDNS(tmp), "DNSTunneling.OutputPrefix")
		}, func(v string) { cfg.DNSTunneling.OutputPrefix = v })

	fields := []inspector.Field{
		// Resolver
		{Name: "Workers", Description: descResolverWorkers, Group: groupResolver, Input: inspector.Adapt(resolverWorkers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Transport", Description: descResolverTransport, Group: groupResolver, Input: inspector.Adapt(resolverTransport), Visible: alwaysVisible},
		{Name: "Domain", Description: descResolverDomain, Group: groupResolver, Input: inspector.Adapt(resolverDomain), Visible: alwaysVisible},
		{Name: "Port", Description: descResolverPort, Group: groupResolver, Input: inspector.Adapt(resolverPort), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Check Types", Description: descResolverCheckTypes, Group: groupResolver, Input: inspector.Adapt(resolverCheckType), Visible: alwaysVisible, Format: inspector.FormatStringList},
		{Name: "EDNS Buffer Size", Description: descResolverEDNSBufSize, Group: groupResolver, Input: inspector.Adapt(resolverEDNSBufSize), Visible: alwaysVisible, Format: formatEDNS},
		{Name: "Timeout", Description: descResolverTimeout, Group: groupResolver, Input: inspector.Adapt(resolverTimeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "Tries", Description: descResolverTries, Group: groupResolver, Input: inspector.Adapt(resolverTries), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Random Subdomain", Description: descResolverRandomSub, Group: groupResolver, Input: inspector.Adapt(resolverRandomSubdomain), Visible: alwaysVisible, Format: inspector.FormatBool},
		{Name: "Accepted RCodes", Description: descResolverAcceptedRCodes, Group: groupResolver, Input: inspector.Adapt(resolverAcceptedRCodes), Visible: alwaysVisible, Format: inspector.FormatStringList},
		{Name: "Prefix Output", Description: descResolverOutputPrefix, Group: groupResolver, Input: inspector.Adapt(resolverOutputPrefix), Visible: alwaysVisible},

		// DPI
		{Name: "Check DPI", Description: descResolverCheckDPI, Group: groupDPI, Input: inspector.Adapt(resolverCheckDPI), Visible: alwaysVisible, Format: inspector.FormatBool},
		{Name: "DPI Timeout", Description: descResolverDPITimeout, Group: groupDPI, Input: inspector.Adapt(resolverDPITimeout), Visible: dpiEnabled, Format: inspector.FormatDurationMS},
		{Name: "DPI Tries", Description: descResolverDPITries, Group: groupDPI, Input: inspector.Adapt(resolverDPITries), Visible: dpiEnabled, Format: inspector.FormatInt},

		// DNS Tunneling
		{Name: "Workers", Description: descTunnelWorkers, Group: groupDNSTunnel, Input: inspector.Adapt(tunnelWorkers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Tries", Description: descTunnelTries, Group: groupDNSTunnel, Input: inspector.Adapt(tunnelTries), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Timeout", Description: descTunnelTimeout, Group: groupDNSTunnel, Input: inspector.Adapt(tunnelTimeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "Check DNS Resolver", Description: descTunnelCheckDNSResolver, Group: groupDNSTunnel, Input: inspector.Adapt(tunnelCheckDNSResolver), Visible: alwaysVisible, Format: inspector.FormatBool},
		{Name: "Prefix Output", Description: descTunnelOutputPrefix, Group: groupDNSTunnel, Input: inspector.Adapt(tunnelOutputPrefix), Visible: alwaysVisible},
	}

	return &Model{
		state:     state,
		name:      name,
		id:        ui.NewComponentID(),
		inspector: inspector.New(state.Layout, "dns settings", fields),
	}
}

func alwaysVisible() bool { return true }

func toUpper(values []string) []string {
	out := make([]string, len(values))
	for i, v := range values {
		out[i] = strings.ToUpper(v)
	}
	return out
}

func fieldErr(errs map[string]error, field string) error {
	return errs[field]
}

func formatEDNS(v any) string {
	s, ok := v.(string)
	if !ok {
		return ""
	}

	if strings.TrimSpace(s) == "0" {
		return "disabled"
	}

	return inspector.FormatInt(v)
}
