package xray

import (
	"strconv"
	"time"

	"bgscan/internal/core/config"
	"bgscan/internal/core/config/validate"
	"bgscan/internal/logger"
	"bgscan/internal/ui/components/basic/input"
	"bgscan/internal/ui/components/basic/input/selectinput"
	"bgscan/internal/ui/components/basic/input/textinput"
	"bgscan/internal/ui/components/basic/inspector"
	"bgscan/internal/ui/components/basic/notice"
	"bgscan/internal/ui/shared/env"
	"bgscan/internal/ui/shared/ui"

	tea "charm.land/bubbletea/v2"
	"charm.land/huh/v2"
)

const groupXray = "Xray Settings"

const (
	descWorkers              = "The number of concurrent workers performing Xray connectivity tests. Higher values increase test throughput at the cost of greater bandwidth and CPU utilization."
	descConnectivityTestType = "The type of connectivity test to perform: 0 (Connectivity only), 1 (Download only), 2 (Upload only), or 3 (Both)."
	descDownloadSpeed        = "Target download speed (in kbps) to test against within the configured timeout. Used when connectivity test type includes download."
	descUploadSpeed          = "Target upload speed (in kbps) to test against within the configured timeout. Used when connectivity test type includes upload."
	descTimeout              = "Maximum duration in milliseconds to wait for an Xray connectivity test to complete. Tests failing to respond within this window are considered failed."
	descOutputPrefix         = "The filename prefix applied to all output files generated by this module, allowing easy identification when running multiple scans."
	descPreScanType          = "The pre-scan connectivity test to perform before running Xray: 'none' (skip), 'icmp', 'tcp', or 'http'."
)

type Model struct {
	state     *ui.AppState
	name      string
	id        ui.ComponentID
	inspector ui.Component
}

func (m *Model) ID() ui.ComponentID { return m.id }
func (m *Model) Init() tea.Cmd      { return nil }
func (m *Model) Mode() env.Mode     { return env.NormalMode }
func (m *Model) Name() string       { return m.name }
func (m *Model) OnClose() tea.Cmd   { return nil }

func saveXray(state *ui.AppState) tea.Cmd {
	if err := state.Store.SaveXray(state.Config.Xray); err != nil {
		logger.UIError("Failed to save Xray settings: %v", err)
		return notice.NewNoticeCmd(state.Layout, "Failed to save Xray settings", err.Error(), notice.NOTICE_ERROR)
	}
	return nil
}

func intInput(state *ui.AppState, title string, value int, val func(string) error, set func(int)) input.Input[string] {
	return textinput.New(
		state.Layout, title,
		textinput.WithValue(strconv.Itoa(value)),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(state.Layout, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(n)
			return saveXray(state)
		}),
	)
}

func durationMSInput(state *ui.AppState, title string, value time.Duration, val func(string) error, set func(time.Duration)) input.Input[string] {
	return textinput.New(
		state.Layout, title,
		textinput.WithValue(strconv.FormatInt(value.Milliseconds(), 10)),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			n, err := strconv.Atoi(v)
			if err != nil {
				return notice.NewNoticeCmd(state.Layout, "Invalid "+title, err.Error(), notice.NOTICE_ERROR)
			}
			set(time.Duration(n) * time.Millisecond)
			return saveXray(state)
		}),
	)
}

func stringInput(state *ui.AppState, title, value string, val func(string) error, set func(string)) input.Input[string] {
	return textinput.New(
		state.Layout, title,
		textinput.WithValue(value),
		textinput.WithValidation(val),
		textinput.WithFocus(),
		textinput.WithOnSubmit(func(v string) tea.Cmd {
			set(v)
			return saveXray(state)
		}),
	)
}

func New(state *ui.AppState, name string) *Model {
	cfg := &state.Config.Xray

	workers := intInput(state, "Enter number of workers", cfg.Workers,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Workers = n
			return fieldErr(validate.ValidateXray(tmp), "Workers")
		},
		func(n int) { cfg.Workers = n })

	connectivityTestType := selectinput.New(
		state.Layout, "Select connectivity test type",
		selectinput.WithValue(cfg.ConnectivityTestType),
		selectinput.WithFocus[config.ConnectivityTest](),
		selectinput.WithOptions(
			huh.NewOption("Connectivity Only", config.ConnectivityOnly),
			huh.NewOption("Download Speed Only", config.DownloadSpeedOnly),
			huh.NewOption("Upload Speed Only", config.UploadSpeedOnly),
			huh.NewOption("Both", config.Both),
		),
		selectinput.WithOnSubmit(func(v config.ConnectivityTest) tea.Cmd {
			cfg.ConnectivityTestType = v
			return saveXray(state)
		}),
	)

	includesDownload := func() bool {
		return cfg.ConnectivityTestType == config.DownloadSpeedOnly || cfg.ConnectivityTestType == config.Both
	}
	includesUpload := func() bool {
		return cfg.ConnectivityTestType == config.UploadSpeedOnly || cfg.ConnectivityTestType == config.Both
	}

	downloadSpeed := intInput(state, "Enter download speed (kbps)", cfg.DownloadSpeed,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.DownloadSpeed = n
			return fieldErr(validate.ValidateXray(tmp), "DownloadSpeed")
		},
		func(n int) { cfg.DownloadSpeed = n })

	uploadSpeed := intInput(state, "Enter upload speed (kbps)", cfg.UploadSpeed,
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.UploadSpeed = n
			return fieldErr(validate.ValidateXray(tmp), "UploadSpeed")
		},
		func(n int) { cfg.UploadSpeed = n })

	timeout := durationMSInput(state, "Enter timeout (milliseconds)", cfg.Timeout.Duration(),
		func(v string) error {
			n, err := strconv.Atoi(v)
			if err != nil {
				return err
			}
			tmp := *cfg
			tmp.Timeout = config.NewDurationMS(time.Duration(n) * time.Millisecond)
			return fieldErr(validate.ValidateXray(tmp), "Timeout")
		},
		func(d time.Duration) { cfg.Timeout = config.NewDurationMS(d) })

	preScanType := selectinput.New(
		state.Layout, "Select pre-scan type",
		selectinput.WithValue(cfg.PreScanType),
		selectinput.WithFocus[string](),
		selectinput.WithOptions(
			huh.NewOption("None", "none"),
			huh.NewOption("ICMP", "icmp"),
			huh.NewOption("TCP", "tcp"),
			huh.NewOption("HTTP", "http"),
		),
		selectinput.WithOnSubmit(func(v string) tea.Cmd {
			cfg.PreScanType = v
			return saveXray(state)
		}),
	)

	prefixOutput := stringInput(state, "Enter output file prefix", cfg.OutputPrefix,
		func(v string) error {
			tmp := *cfg
			tmp.OutputPrefix = v
			return fieldErr(validate.ValidateXray(tmp), "OutputPrefix")
		},
		func(v string) { cfg.OutputPrefix = v })

	fields := []inspector.Field{
		{Name: "Workers", Description: descWorkers, Group: groupXray, Input: inspector.Adapt(workers), Visible: alwaysVisible, Format: inspector.FormatInt},
		{Name: "Connectivity Test Type", Description: descConnectivityTestType, Group: groupXray, Input: inspector.Adapt(connectivityTestType), Visible: alwaysVisible},
		{Name: "Download Speed", Description: descDownloadSpeed, Group: groupXray, Input: inspector.Adapt(downloadSpeed), Visible: includesDownload, Format: inspector.FormatDataSpeed},
		{Name: "Upload Speed", Description: descUploadSpeed, Group: groupXray, Input: inspector.Adapt(uploadSpeed), Visible: includesUpload, Format: inspector.FormatDataSpeed},
		{Name: "Timeout", Description: descTimeout, Group: groupXray, Input: inspector.Adapt(timeout), Visible: alwaysVisible, Format: inspector.FormatDurationMS},
		{Name: "Pre-Scan Type", Description: descPreScanType, Group: groupXray, Input: inspector.Adapt(preScanType), Visible: alwaysVisible},
		{Name: "Prefix Output", Description: descOutputPrefix, Group: groupXray, Input: inspector.Adapt(prefixOutput), Visible: alwaysVisible},
	}

	return &Model{
		state:     state,
		name:      name,
		id:        ui.NewComponentID(),
		inspector: inspector.New(state.Layout, "xray settings", fields),
	}
}

func alwaysVisible() bool { return true }

func fieldErr(errs map[string]error, field string) error {
	return errs[field]
}
